import Foundation
import Combine

enum AppLanguageMode: String, CaseIterable, Codable, Identifiable {
    case followSystem
    case english
    case simplifiedChinese

    var id: String { rawValue }
}

extension Notification.Name {
    static let appPreferencesLanguageDidChange = Notification.Name("appPreferencesLanguageDidChange")
}

enum AppColorSchemeMode: String, CaseIterable, Codable, Identifiable {
    case followSystem
    case light
    case dark

    var id: String { rawValue }

}

enum AppVoiceSource: String, CaseIterable, Codable, Identifiable {
    case followSystem
    case bestInstalled
    case chosenVoice

    var id: String { rawValue }
}

enum AppDefaultProjectMode: String, CaseIterable, Codable, Identifiable {
    case lastActive
    case defaultWorkspace

    var id: String { rawValue }
}

@MainActor
final class AppPreferences: ObservableObject {
    @Published var languageMode: AppLanguageMode {
        didSet {
            defaults.set(languageMode.rawValue, forKey: Keys.languageMode)
            NotificationCenter.default.post(name: .appPreferencesLanguageDidChange, object: nil)
        }
    }

    @Published var colorSchemeMode: AppColorSchemeMode {
        didSet { defaults.set(colorSchemeMode.rawValue, forKey: Keys.colorSchemeMode) }
    }

    @Published var reduceMotion: Bool {
        didSet { defaults.set(reduceMotion, forKey: Keys.reduceMotion) }
    }

    @Published var autoReadReplies: Bool {
        didSet { defaults.set(autoReadReplies, forKey: Keys.autoReadReplies) }
    }

    @Published var voiceSource: AppVoiceSource {
        didSet { defaults.set(voiceSource.rawValue, forKey: Keys.voiceSource) }
    }

    @Published var chosenVoiceIdentifier: String? {
        didSet { defaults.set(chosenVoiceIdentifier, forKey: Keys.chosenVoiceIdentifier) }
    }

    @Published var speechRate: Double {
        didSet { defaults.set(speechRate, forKey: Keys.speechRate) }
    }

    @Published var speechVolume: Double {
        didSet { defaults.set(speechVolume, forKey: Keys.speechVolume) }
    }

    @Published var rememberLastAgent: Bool {
        didSet { defaults.set(rememberLastAgent, forKey: Keys.rememberLastAgent) }
    }

    @Published var defaultProjectMode: AppDefaultProjectMode {
        didSet { defaults.set(defaultProjectMode.rawValue, forKey: Keys.defaultProjectMode) }
    }

    @Published var includeActiveAppContext: Bool {
        didSet { defaults.set(includeActiveAppContext, forKey: Keys.includeActiveAppContext) }
    }

    @Published var includeBrowserContext: Bool {
        didSet { defaults.set(includeBrowserContext, forKey: Keys.includeBrowserContext) }
    }

    private let defaults: UserDefaults

    init(defaults: UserDefaults = .standard) {
        self.defaults = defaults
        languageMode = Self.decode(defaults.string(forKey: Keys.languageMode), fallback: .followSystem)
        colorSchemeMode = Self.decode(defaults.string(forKey: Keys.colorSchemeMode), fallback: .followSystem)
        reduceMotion = defaults.object(forKey: Keys.reduceMotion) as? Bool ?? false
        autoReadReplies = defaults.object(forKey: Keys.autoReadReplies) as? Bool ?? true
        voiceSource = Self.decode(defaults.string(forKey: Keys.voiceSource), fallback: .followSystem)
        chosenVoiceIdentifier = defaults.string(forKey: Keys.chosenVoiceIdentifier)
        speechRate = defaults.object(forKey: Keys.speechRate) as? Double ?? 0.48
        speechVolume = defaults.object(forKey: Keys.speechVolume) as? Double ?? 1.0
        rememberLastAgent = defaults.object(forKey: Keys.rememberLastAgent) as? Bool ?? true
        defaultProjectMode = Self.decode(defaults.string(forKey: Keys.defaultProjectMode), fallback: .lastActive)
        includeActiveAppContext = defaults.object(forKey: Keys.includeActiveAppContext) as? Bool ?? true
        includeBrowserContext = defaults.object(forKey: Keys.includeBrowserContext) as? Bool ?? false
    }

    var resolvedLocaleIdentifier: String {
        Self.resolveLocaleIdentifier(
            mode: languageMode,
            preferredLanguages: Locale.preferredLanguages
        )
    }

    func text(_ key: String) -> String {
        Self.localizedString(key, localeIdentifier: resolvedLocaleIdentifier)
    }

    nonisolated static func resolveLocaleIdentifier(
        mode: AppLanguageMode,
        preferredLanguages: [String]
    ) -> String {
        switch mode {
        case .english:
            return "en"
        case .simplifiedChinese:
            return "zh-Hans"
        case .followSystem:
            let first = preferredLanguages.first?.lowercased() ?? ""
            return first.hasPrefix("zh") ? "zh-Hans" : "en"
        }
    }

    nonisolated static func localizedString(_ key: String, localeIdentifier: String) -> String {
        if let localized = localizedStrings[localeIdentifier]?[key] {
            return localized
        }
        if let english = localizedStrings["en"]?[key] {
            return english
        }
        return key
    }

    private nonisolated static func decode<T: RawRepresentable>(
        _ rawValue: String?,
        fallback: T
    ) -> T where T.RawValue == String {
        guard let rawValue, let decoded = T(rawValue: rawValue) else {
            return fallback
        }
        return decoded
    }

    private enum Keys {
        static let languageMode = "preferences.languageMode"
        static let colorSchemeMode = "preferences.colorSchemeMode"
        static let reduceMotion = "preferences.reduceMotion"
        static let autoReadReplies = "preferences.autoReadReplies"
        static let voiceSource = "preferences.voiceSource"
        static let chosenVoiceIdentifier = "preferences.chosenVoiceIdentifier"
        static let speechRate = "preferences.speechRate"
        static let speechVolume = "preferences.speechVolume"
        static let rememberLastAgent = "preferences.rememberLastAgent"
        static let defaultProjectMode = "preferences.defaultProjectMode"
        static let includeActiveAppContext = "preferences.includeActiveAppContext"
        static let includeBrowserContext = "preferences.includeBrowserContext"
    }
}

extension AppLanguageMode {
    @MainActor
    func title(preferences: AppPreferences) -> String {
        switch self {
        case .followSystem: return preferences.text("language.followSystem")
        case .english: return preferences.text("language.english")
        case .simplifiedChinese: return preferences.text("language.simplifiedChinese")
        }
    }
}

extension AppColorSchemeMode {
    @MainActor
    func title(preferences: AppPreferences) -> String {
        switch self {
        case .followSystem: return preferences.text("appearance.followSystem")
        case .light: return preferences.text("appearance.light")
        case .dark: return preferences.text("appearance.dark")
        }
    }
}

extension AppVoiceSource {
    @MainActor
    func title(preferences: AppPreferences) -> String {
        switch self {
        case .followSystem: return preferences.text("voice.source.system")
        case .bestInstalled: return preferences.text("voice.source.best")
        case .chosenVoice: return preferences.text("voice.source.choose")
        }
    }
}

extension AppDefaultProjectMode {
    @MainActor
    func title(preferences: AppPreferences) -> String {
        switch self {
        case .lastActive: return preferences.text("conversation.lastActiveProject")
        case .defaultWorkspace: return preferences.text("conversation.defaultWorkspace")
        }
    }
}

private let localizedStrings: [String: [String: String]] = [
    "en": [
        "settings.title": "Settings",
        "settings.subtitle": "Personal preferences for how the assistant feels, speaks, opens, and uses lightweight context.",
        "settings.diagnostics": "Diagnostics",
        "settings.models": "Models",
        "settings.capabilities": "Capabilities",
        "settings.mcp": "MCP",
        "settings.plugins": "Plugins",
        "settings.tools": "Tools",
        "settings.preferences": "Settings",
        "settings.savedLocally": "Preferences saved locally",
        "settings.close": "Close",
        "settings.refresh": "Refresh",
        "diagnostics.title": "Startup Diagnostics",
        "diagnostics.subtitle": "Check backend health, local paths, provider readiness, and packaged-app runtime state.",
        "diagnostics.status": "Status",
        "diagnostics.passed": "Passed",
        "diagnostics.warnings": "Warnings",
        "diagnostics.failed": "Failed",
        "diagnostics.checks": "Checks",
        "diagnostics.checks.subtitle": "Read-only startup checks with concrete repair hints.",
        "diagnostics.paths": "Local Paths",
        "diagnostics.paths.subtitle": "App-owned data locations used by the packaged runtime.",
        "diagnostics.runtime": "Runtime",
        "diagnostics.runtime.subtitle": "Current backend process and task persistence state.",
        "diagnostics.tasks": "Tasks",
        "diagnostics.persistence": "Persistence",
        "diagnostics.uptime": "Uptime",
        "diagnostics.headline.passed": "%d passed",
        "diagnostics.headline.warnings": "%d warning(s)",
        "diagnostics.headline.failed": "%d failed",
        "diagnostics.loading": "Loading startup diagnostics...",
        "diagnostics.empty": "No diagnostics loaded yet.",
        "diagnostics.openPath": "Open folder",
        "diagnostics.status.ready": "Ready",
        "diagnostics.status.attention": "Attention",
        "diagnostics.status.blocked": "Blocked",
        "diagnostics.status.passed": "Passed",
        "diagnostics.status.warning": "Warning",
        "diagnostics.status.failed": "Failed",
        "diagnostics.status.info": "Info",
        "releaseVerification.title": "RC Verification",
        "releaseVerification.subtitle": "Generate a release report from startup diagnostics and the latest Release E2E evidence.",
        "releaseVerification.run": "Run RC Check",
        "releaseVerification.running": "Running...",
        "releaseVerification.empty": "No RC verification report yet.",
        "releaseVerification.latest": "Latest Release E2E",
        "releaseVerification.reportFiles": "Report Files",
        "releaseVerification.remediation": "Remediation",
        "releaseVerification.task": "Task",
        "releaseVerification.benchmark": "Benchmark",
        "releaseVerification.score": "Score",
        "releaseVerification.repairs": "Repairs",
        "releaseVerification.preReleaseGates": "Pre-Release Gates",
        "releaseVerification.gateSummary": "%d passed · %d configured · %d manual · %d missing",
        "releaseVerification.missingGatePaths": "Missing required gate paths",
        "releaseVerification.gateParseErrors": "Gate evidence parse errors",
        "releaseVerification.morePaths": "%d more paths",
        "releaseVerification.gateEvidence": "Evidence",
        "releaseVerification.gateStatus.configured": "Configured",
        "releaseVerification.gateStatus.passed": "Passed",
        "releaseVerification.gateStatus.manual_required": "Manual",
        "releaseVerification.gateStatus.missing": "Missing",
        "releaseVerification.gateStatus.failed": "Failed",
        "releaseVerification.gateStatus.blocked": "Blocked",
        "releaseVerification.markdown": "Markdown",
        "releaseVerification.json": "JSON",
        "releaseVerification.openReport": "Open report",
        "section.language": "Language",
        "section.voice": "Voice & Reading",
        "section.appearance": "Appearance",
        "section.window": "Window & Shortcuts",
        "section.conversation": "Conversation Defaults",
        "section.privacy": "Privacy & Context",
        "section.advanced": "Advanced",
        "language.mode": "App language",
        "language.mode.help": "Follow macOS when possible. Unsupported languages fall back to English.",
        "language.followSystem": "Follow System",
        "language.english": "English",
        "language.simplifiedChinese": "简体中文",
        "voice.summary": "Current voice",
        "voice.source": "Voice source",
        "voice.source.help": "Use the macOS system voice, the best installed voice, or a chosen installed voice.",
        "voice.source.system": "System",
        "voice.source.best": "Best",
        "voice.source.choose": "Choose",
        "voice.autoRead": "Auto-read assistant replies",
        "voice.autoRead.help": "Speak new assistant messages unless the chat is muted.",
        "voice.rate": "Speaking rate",
        "voice.volume": "Volume",
        "voice.test": "Test Voice",
        "voice.openSettings": "Open Voice Settings",
        "voice.refresh": "Refresh Voices",
        "voice.available": "Available",
        "voice.noVoices": "No voices found",
        "voice.systemDefault": "System default",
        "voice.bestInstalled": "Best installed",
        "appearance.scheme": "Color scheme",
        "appearance.scheme.help": "Match macOS or keep the assistant in a fixed theme.",
        "appearance.followSystem": "Follow System",
        "appearance.light": "Light",
        "appearance.dark": "Dark",
        "appearance.reduceMotion": "Reduce motion",
        "appearance.reduceMotion.help": "Reduce non-essential animations such as hover, panel, and status transitions.",
        "conversation.rememberAgent": "Remember last selected Agent",
        "conversation.rememberAgent.help": "Prefer your last Agent when it is still available.",
        "conversation.defaultProject": "Default project",
        "conversation.defaultProject.help": "Choose where new conversations begin.",
        "conversation.lastActiveProject": "Last active project",
        "conversation.defaultWorkspace": "Default workspace",
        "privacy.activeApp": "Attach active app context",
        "privacy.activeApp.help": "Include the foreground app and window title when available.",
        "privacy.browser": "Attach browser context",
        "privacy.browser.help": "Reserved for browser title and URL context.",
        "privacy.openData": "Open Data Folder",
        "advanced.socket": "Backend socket",
        "advanced.logs": "Logs folder",
        "advanced.openLogs": "Open Logs",
        "screenshot.ocr": "Screenshot OCR",
        "screenshot.attach": "Attach Screenshot",
        "screenshot.copy": "Copy Screenshot",
        "screenshot.copied": "Screenshot copied to clipboard.",
        "screenshot.cancelled": "Screenshot cancelled.",
        "screenshot.copyFailed": "Could not copy screenshot to clipboard.",
        "screenshot.permission.ocr": "[Tip: The first screenshot requires Screen Recording permission. Allow it in the system prompt, or enable it in System Settings -> Privacy & Security -> Screen Recording. Restart the app after granting permission.]",
        "screenshot.permission.attach": "[Tip: Screenshot attachment requires Screen Recording permission. Allow it in System Settings -> Privacy & Security -> Screen Recording, then try again.]",
        "screenshot.permission.copy": "[Tip: Copy screenshot requires Screen Recording permission. Allow it in System Settings -> Privacy & Security -> Screen Recording, then try again.]",
        "toolbar.voiceInput": "Voice input",
        "toolbar.continuous.enable": "Enable continuous voice mode",
        "toolbar.continuous.disable": "Disable continuous voice mode",
        "toolbar.mute": "Mute voice output",
        "toolbar.unmute": "Unmute voice output",
        "toolbar.copyConversation": "Copy full conversation",
        "toolbar.tasks": "Tasks",
        "toolbar.tasks.disabled": "Configure an available Agent or LLM first",
        "toolbar.models": "Models",
        "toolbar.capabilities": "Capabilities",
        "toolbar.mcp": "MCP Plugins",
        "toolbar.plugins": "Plugin Center",
        "toolbar.tools": "Tool Permissions",
        "toolbar.settings": "Settings",
        "attachment.addFiles": "Attach files or folders",
        "project.title": "Projects",
        "project.new": "New Project",
        "project.newBlank": "New Blank Project",
        "project.useExisting": "Use Existing Folder",
        "project.loading": "Loading projects...",
        "project.back": "Back to Projects",
        "project.collapseAll": "Collapse All",
        "project.refresh": "Refresh",
        "project.hideHidden": "Hide Hidden Files",
        "project.showHidden": "Show Hidden Files",
        "project.newChat": "New Chat",
        "project.newChatInProject": "New Chat in This Project",
        "project.openTree": "Open Directory Tree",
        "project.noChats": "No chats yet",
        "project.pin": "Pin Project",
        "project.unpin": "Unpin Project",
        "conversation.pin": "Pin Conversation",
        "conversation.unpin": "Unpin Conversation",
        "conversation.rename": "Rename",
        "conversation.sessionName": "Session name",
        "conversation.newConversation": "New conversation",
        "conversation.deleteSession": "Delete Session",
        "conversation.deleteSessions": "Delete %d Sessions",
        "conversation.yesterday": "Yesterday",
        "chat.loadEarlier": "Load earlier messages...",
        "chat.thinking": "Thinking...",
        "chat.stop": "Stop generation",
        "chat.checkingAgents": "Checking Agents...",
        "chat.configureModel": "Configure a Model",
        "chat.assistant": "Assistant",
        "chat.placeholder.checking": "Checking available agents...",
        "chat.placeholder.noAgent": "No available agent. Open Model Settings to continue.",
        "chat.placeholder.project": "Ask about %@...",
        "chat.placeholder.selectProject": "Select a project to start chatting...",
        "onboarding.noAgent": "No Available Agent or LLM",
        "onboarding.noAgent.help": "Open Model Settings and configure at least one cloud LLM or local agent before chatting or creating tasks.",
        "onboarding.openModels": "Open Model Settings",
        "onboarding.checking": "Checking available agents and LLMs...",
        "accessibility.title": "Accessibility Permission Required",
        "accessibility.message": "Across Agents Assistant needs Accessibility permission to read contextual screen information, such as the current browser URL or selected Finder files.\n\nEnable this app in System Settings, then try again.",
        "system.cancel": "Cancel",
        "system.save": "Save",
        "system.delete": "Delete",
        "system.retry": "Retry",
        "system.browse": "Browse",
        "system.yes": "yes",
        "system.no": "no",
        "system.submit": "Submit",
        "system.submitting": "Submitting...",
        "system.ready": "ready",
        "system.openSystemSettings": "Open System Settings",
        "menubar.tooltip": "Across Agents Assistant",
        "menubar.showWindow": "Show Main Window",
        "menubar.togglePanel": "Toggle Panel (Option+Tab)",
        "menubar.quit": "Quit",
        "models.title": "Model Settings",
        "models.localAgent": "LOCAL AGENT",
        "models.cloudLLM": "CLOUD LLM",
        "models.refreshAll": "Refresh All",
        "models.configured": "Configured",
        "models.notConfigured": "Not configured",
        "models.executablePath": "Executable Path",
        "models.chooseExecutable": "Choose executable",
        "models.autoDetect": "Auto Detect",
        "models.detecting": "Detecting",
        "models.detectingExecutable": "Detecting executable...",
        "models.detectAgent.help": "Detect this agent from configured path, PATH, and safe system locations",
        "models.apiKey": "API Key",
        "models.baseURL": "Base URL",
        "models.model": "Model",
        "models.autoModel": "auto",
        "models.refreshModels": "Refresh model list",
        "models.advancedParameters": "Advanced Parameters",
        "models.temperature": "Temperature",
        "models.hideApiKey": "Hide API key",
        "models.showApiKey": "Show API key",
        "models.deleteConfiguration": "Delete Configuration",
        "models.deleteConfiguration.message": "Are you sure you want to delete the %@ configuration? This will remove the API key from the local credential store.",
        "models.status.notFound": "Not found",
        "models.status.notAuthenticated": "Not authenticated",
        "models.status.unavailable": "Unavailable",
        "models.status.invalidPath": "Invalid path",
        "models.warning.invalidPath": "The configured executable path is invalid. Choose a valid executable or leave it empty to use Auto Detect.",
        "models.warning.unavailable": "Installed, but health check failed. Make sure the agent is signed in and can complete a non-interactive task.",
        "models.warning.claudeAuth": "Run claude auth in terminal.",
        "models.detected": "Detected%@.",
        "models.detected.at": " at %@",
        "models.notFoundManual": "No executable found. Choose a path manually if it is installed elsewhere.",
        "models.detectedVia": "Detected via %@: %@",
        "models.detectedPath": "Detected path: %@",
        "models.configuredPath": "Configured path: %@",
        "models.noExecutable": "No executable found. Leave empty to auto-detect from PATH, or choose the executable manually.",
        "models.autoDetectPath": "Auto detect from PATH",
        "models.chooseExecutableTitle": "Choose %@ Executable",
        "models.choose": "Choose",
        "mcp.title": "MCP Plugins",
        "mcp.connected": "Connected",
        "mcp.connecting": "Connecting",
        "mcp.failed": "Failed",
        "mcp.disabled": "Disabled",
        "mcp.disconnected": "Not connected",
        "mcp.needsConfiguration": "Needs configuration",
        "mcp.endpointPlaceholder": "Enter API Endpoint URL",
        "mcp.noPath": "No path configured",
        "mcp.noConfigurationRequired": "No configuration required",
        "mcp.customConfiguration": "Custom configuration...",
        "mcp.implementation.external": "External Across Context plugin",
        "mcp.implementation.standard": "Standard MCP server",
        "mcp.plugin.local_kb.name": "Local Knowledge Base",
        "mcp.plugin.local_kb.description": "Search local notes and knowledge files through MCP.",
        "mcp.plugin.external_rag.name": "External RAG",
        "mcp.plugin.external_rag.description": "Connect an external retrieval endpoint for richer context.",
        "mcp.plugin.sqlite.name": "SQLite",
        "mcp.plugin.sqlite.description": "Let agents inspect and query a local SQLite database.",
        "mcp.plugin.filesystem.name": "Filesystem",
        "mcp.plugin.filesystem.description": "Give agents scoped access to files and folders.",
        "mcp.plugin.across_context.name": "Across Context",
        "mcp.plugin.across_context.description": "Share durable local memory across configured coding agents.",
        "plugins.title": "Plugin Center",
        "plugins.subtitle": "Manage external Across plugins, lifecycle actions, and shared memory governance.",
        "plugins.versionUnknown": "Version unknown",
        "plugins.commandReady": "Command ready",
        "plugins.commandMissing": "Command missing",
        "plugins.manifestReady": "Manifest ready",
        "plugins.manifestMissing": "Manifest missing",
        "plugins.path.runtime": "Runtime",
        "plugins.path.data": "Data",
        "plugins.compatibility": "Requires host",
        "plugins.status.ready": "Ready",
        "plugins.status.installed": "Installed",
        "plugins.status.missing": "Missing",
        "plugins.action.probe": "Probe",
        "plugins.action.install": "Install",
        "plugins.action.repair": "Repair",
        "plugins.action.uninstall": "Uninstall",
        "plugins.loop.runtime": "Agent Loop",
        "plugins.loop.v2": "Loop v2",
        "plugins.loop.checkpoints": "Checkpoints",
        "plugins.loop.memoryHooks": "Memory hooks",
        "plugins.loop.probe": "Run Agent Loop Probe",
        "plugins.loop.status": "Loop %@",
        "plugins.loop.steps": "%d steps",
        "plugins.loop.checkpointCount": "%d checkpoints",
        "plugins.loop.currentAction": "Action %@",
        "plugins.loop.pendingApproval": "Approval pending",
        "plugins.loop.leaseRemaining": "%ds lease",
        "plugins.loop.leaseIdle": "Lease idle",
        "plugins.loop.leaseStale": "Lease stale",
        "plugins.loop.cancelRequested": "Cancel requested",
        "plugins.loop.cancelAckPending": "Cancel pending",
        "plugins.loop.failureCount": "%d failures",
        "plugins.loop.healthDetails": "Loop health details",
        "plugins.loop.detailStatus": "Status",
        "plugins.loop.detailAction": "Action",
        "plugins.loop.detailLease": "Lease",
        "plugins.loop.detailHeartbeat": "Heartbeat",
        "plugins.loop.detailCancellation": "Cancellation",
        "plugins.loop.detailFailures": "Failures",
        "plugins.loop.detailExecutableActions": "Actions",
        "plugins.loop.detailReleaseEvidence": "Release",
        "plugins.loop.detailReleaseCheck": "Check",
        "plugins.loop.detailReleaseRisk": "Risk",
        "plugins.loop.detailReleaseNext": "Next",
        "plugins.loop.detailAudit": "Audit",
        "plugins.loop.detailRouting": "Routing",
        "plugins.loop.detailRecovery": "Recovery",
        "plugins.loop.detailRecoveryPolicy": "Policy",
        "plugins.loop.detailRecoveredStep": "Recovered",
        "plugins.loop.detailMemory": "Memory",
        "plugins.loop.detailMemoryCandidate": "Candidate",
        "plugins.loop.evidenceDetails": "Evidence details",
        "plugins.loop.auditComplete": "%d events complete",
        "plugins.loop.auditPartial": "%d events partial",
        "plugins.loop.routingSummary": "%d routed, %d hints",
        "plugins.loop.recoverySummary": "%d decisions, %d applied, %d blocked",
        "plugins.loop.recoveryApplied": "applied",
        "plugins.loop.recoveryBlocked": "blocked",
        "plugins.loop.recoveryAttempt": "attempt %d/%d",
        "plugins.loop.recoveryAttemptSingle": "attempt %d",
        "plugins.loop.recoveryMore": "+%d more",
        "plugins.loop.recoveredAfter": "%@ after %@",
        "plugins.loop.recoveryTurn": "turn %d",
        "plugins.loop.memoryCandidateSummary": "%d candidates",
        "plugins.loop.memoryCandidateTurn": "turn %d",
        "plugins.loop.releaseEvidenceWithRisks": "%@, %d risks",
        "plugins.loop.evidenceMore": "+%d more",
        "plugins.loop.renewalCount": "%d renewals",
        "plugins.loop.none": "None",
        "plugins.loop.events": "Events",
        "plugins.loop.eventsLive": "Live",
        "plugins.loop.eventsSnapshot": "Snapshot",
        "plugins.loop.eventsFallback": "Fallback",
        "plugins.loop.eventsUnavailable": "Unavailable",
        "plugins.loop.timelineMode": "Timeline mode",
        "plugins.loop.eventSequence": "Sequence",
        "plugins.loop.eventId": "Event ID",
        "plugins.loop.correlationId": "Correlation",
        "plugins.loop.stepId": "Step ID",
        "plugins.loop.actionId": "Action ID",
        "plugins.loop.taskId": "Task ID",
        "plugins.loop.subtaskId": "Subtask ID",
        "plugins.memory.title": "Shared Memory Review",
        "plugins.memory.subtitle": "Approve, archive, or forget memories written by Across Context.",
        "plugins.memory.pending": "Pending",
        "plugins.memory.active": "Active",
        "plugins.memory.archived": "Archived",
        "plugins.memory.all": "All",
        "plugins.memory.placeholder": "Add a pending memory for review...",
        "plugins.memory.add": "Add memory",
        "plugins.memory.empty": "No memories match this filter.",
        "plugins.memory.loopCandidates": "Loop memory candidates",
        "plugins.memory.loopCandidateCount": "%d candidates",
        "plugins.memory.focusCandidate": "Focus memory review",
        "plugins.memory.approve": "Approve",
        "plugins.memory.archive": "Archive",
        "plugins.memory.forget": "Forget",
        "capabilities.title": "Agent Capabilities",
        "capabilities.subtitle": "Tune skills, plugins, and tool scope for each agent.",
        "capabilities.agents": "AGENTS",
        "capabilities.agent.local.available": "Local agent available",
        "capabilities.agent.local.configurable": "Local agent configurable",
        "capabilities.agent.cloud.available": "Cloud LLM configured",
        "capabilities.agent.cloud.configurable": "Cloud LLM configurable",
        "capabilities.configuredCount": "%d capabilities configured",
        "capabilities.registry": "Orchestrator Registry",
        "capabilities.registryAgents": "%d agents",
        "capabilities.registryCapabilities": "%d exported capabilities",
        "capabilities.registryRedacted": "redacted",
        "capabilities.registryDescriptor": "Signals",
        "capabilities.registryAliases": "Aliases",
        "capabilities.registryPlugins": "Plugins",
        "capabilities.registryTools": "Tools",
        "capabilities.registryWarnings": "Warnings",
        "capabilities.registryEmpty": "No exported descriptor for this agent.",
        "capabilities.registryRefresh": "Refresh registry",
        "capabilities.registrySynced": "Registry synced",
        "capabilities.registryDrift": "Registry drift detected",
        "capabilities.registryMissing": "Registry descriptor missing",
        "capabilities.registryIssueCount": "%d checks",
        "capabilities.registryExpected": "Expected",
        "capabilities.registryExported": "Exported",
        "capabilities.registryNone": "none",
        "capabilities.registryCheck.descriptor": "Descriptor",
        "capabilities.registryCheck.skills": "Skills",
        "capabilities.registryCheck.plugins": "Plugins",
        "capabilities.registryCheck.tools": "Tools",
        "capabilities.registryCheck.nativeSkills": "Native skills",
        "capabilities.registryCheck.strictScope": "Strict scope",
        "capabilities.reset": "Reset profile",
        "capabilities.skills": "Skills",
        "capabilities.plugins": "MCP Plugins",
        "capabilities.tools": "Tools",
        "capabilities.searchTools": "Search tools",
        "capabilities.instructions": "Custom Instructions",
        "capabilities.strictScope": "Strict plugin/tool scope",
        "capabilities.strictScope.help": "Prefer only the selected plugins and tools for this agent.",
        "capabilities.empty": "Select an agent to configure capabilities.",
        "capabilities.customSkillCount": "%d custom skills",
        "capabilities.addSkill": "Add Skill",
        "capabilities.customSkill": "Custom",
        "capabilities.deleteSkill": "Delete skill",
        "capabilities.newSkill": "New Custom Skill",
        "capabilities.skillName": "Name",
        "capabilities.skillDescription": "Description",
        "capabilities.skillPromptHint": "Prompt Guidance",
        "capabilities.skillTags": "Tags",
        "capabilities.skillTags.placeholder": "frontend, quality",
        "capabilities.createSkill": "Create",
        "capabilities.nativeSkills": "Native Skills",
        "capabilities.nativeSkillCount": "%d installed",
        "capabilities.nativeSkills.empty": "No native skills installed.",
        "capabilities.nativeSkills.create": "Create Claude Skill",
        "capabilities.nativeSkills.install": "Install Native Skill",
        "capabilities.nativeSkills.identifier": "Skill identifier",
        "capabilities.nativeSkills.force": "Force",
        "capabilities.nativeSkills.apply": "Apply",
        "capabilities.nativeSkills.update": "Update skill",
        "capabilities.nativeSkills.uninstall": "Uninstall skill",
        "capabilities.nativeSkills.health": "Available native skills / total native skills",
        "capabilities.nativeSkills.mode.directory": "Directory",
        "capabilities.nativeSkills.mode.cli": "CLI",
        "capabilities.nativeSkills.source.native": "native",
        "capabilities.nativeSkills.unavailable": "Unavailable",
        "tools.title": "Tool Permissions",
        "tools.empty.title": "No Authorized Tools",
        "tools.empty.description": "Tools appear here after you approve them with \"Don't ask again\" enabled.",
        "tools.noData": "No data",
        "tools.parseFailed": "Parse failed: %@",
        "tools.today": "Today %@",
        "tools.yesterday": "Yesterday %@",
        "tools.filter.all": "All",
        "tools.filter.local": "Local Tools",
        "tools.filter.mcp": "MCP Tools",
        "tools.local.section": "Local Tools",
        "tools.mcp.section": "MCP Tools",
        "tools.local.meta": "Directly operates this Mac · %d tools",
        "tools.mcp.meta": "From configured servers · %d tools",
        "tools.mcp.noRuntimeTools": "No MCP tools are available yet. Configure and connect a server above.",
        "tools.permission.alwaysAllow": "Always",
        "tools.permission.askEveryTime": "Once",
        "tools.permission.unavailable": "Never",
        "tools.risk.low": "Low Risk",
        "tools.risk.medium": "Medium Risk",
        "tools.risk.high": "High Risk",
        "tools.risk.unknown": "Unknown Risk",
        "tools.updateFailed": "Could not update permission: %@",
        "approval.title": "Allow tool call?",
        "approval.tool": "Tool",
        "approval.risk": "Risk",
        "approval.macos": "macOS",
        "approval.macos.system": "System permissions are controlled by macOS.",
        "approval.macos.screenRecording": "Screen Recording permission is controlled by macOS.",
        "approval.macos.accessibility": "Accessibility permission is controlled by macOS.",
        "approval.macos.automation": "Automation permission is controlled by macOS.",
        "approval.deny": "Deny",
        "approval.allowOnce": "Allow Once",
        "approval.alwaysAllow": "Always Allow",
        "tool.name.create_email_draft": "Create Email Draft",
        "tool.name.get_finder_context": "Get Finder Context",
        "tool.name.take_screenshot_and_ocr": "Screenshot OCR",
        "tool.name.read_image_text": "Image OCR",
        "tool.name.verify_tool": "Verify Tool",
        "tool.name.open_url": "Open URL",
        "tool.name.get_current_browser_url": "Get Browser URL",
        "tool.name.get_active_browser_url": "Get Browser URL",
        "tool.name.send_claude_code_prompt": "Send Claude Code Prompt",
        "tool.name.list_directory": "List Directory",
        "tool.name.create_note_draft": "Create Note Draft",
        "tool.name.get_xcode_context": "Get Xcode Context",
        "tool.name.toggle_system_dark_mode": "Toggle Dark Mode",
        "tool.name.set_system_volume": "Set System Volume",
        "tool.name.read_file": "Read File",
        "tool.name.write_file": "Write File",
        "tool.name.edit_file": "Edit File",
        "tool.name.grep": "Search File Content",
        "tool.name.search_files": "Search Files",
        "tool.name.sqlite__read_query": "Run SQL Query",
        "tool.name.sqlite__sqlite_query": "Run SQL Query",
        "tool.name.sqlite__create_table": "Create Database Table",
        "tool.name.sqlite__list_tables": "List Database Tables",
        "tool.name.sqlite__sqlite_list_tables": "List Database Tables",
        "tool.name.sqlite__describe_table": "Describe Table",
        "tool.name.sqlite__sqlite_get_schema": "Describe Table",
        "tool.name.sqlite__append_insight": "Append Insight",
        "tool.name.sqlite__sqlite_sample_table": "Sample Table",
        "tool.name.filesystem__filesystem_read_file": "Read File",
        "tool.name.filesystem__filesystem_write_file": "Write File",
        "tool.name.filesystem__filesystem_list_directory": "List Directory",
        "tool.name.filesystem__filesystem_create_directory": "Create Directory",
        "tool.name.filesystem__filesystem_delete_file": "Delete File",
        "tool.name.filesystem__filesystem_delete_directory": "Delete Directory",
        "tool.name.filesystem__filesystem_move": "Move File",
        "tool.name.filesystem__filesystem_get_file_info": "Get File Info",
        "tool.name.filesystem__get_file_info": "Get File Info",
        "tool.name.filesystem__create_directory": "Create Directory",
        "tool.name.filesystem__move_file": "Move File",
        "tool.name.filesystem__copy_file": "Copy File",
        "tool.name.filesystem__delete_file": "Delete File",
        "tool.name.filesystem__file_tree": "Browse File Tree",
        "tool.name.local_kb__search_local_wiki": "Search Local Knowledge Base",
        "tool.name.local_kb__list_wiki_pages": "List Knowledge Pages",
        "tool.name.local_kb__get_wiki_page": "Open Knowledge Page",
        "tool.name.local_kb__read_wiki_page": "Open Knowledge Page",
        "tool.name.external_rag__search_external_knowledge_base": "Search External Knowledge",
        "tool.name.across_context__remember_context": "Remember Context",
        "tool.name.across_context__search_context": "Search Shared Context",
        "tool.name.across_context__get_project_context": "Get Project Context",
        "tool.name.across_context__review_pending_memories": "Review Pending Memories",
        "tool.name.across_context__approve_memory": "Approve Memory",
        "tool.name.across_context__get_agent_card": "Get Agent Card",
        "tool.name.across_context__export_agent_instructions": "Export Agent Instructions",
        "tool.category.sqlite": "SQLite Operation",
        "tool.category.filesystem": "Filesystem Operation",
        "tool.category.local_kb": "Knowledge Base Operation",
        "tool.category.across_context": "Shared Memory Operation",
        "tool.category.email": "Email Operation",
        "tool.category.browser": "Browser Operation",
        "tool.category.finder": "Finder Operation",
        "tool.category.xcode": "Xcode Operation",
        "tool.category.appearance": "Appearance Setting",
        "tool.category.audio": "Audio Control",
        "tool.category.note": "Note Operation",
        "tool.description.list_directory": "List the contents of a local directory.",
        "tool.description.search_files": "Search files by name pattern.",
        "tool.description.read_file": "Read a local text file.",
        "tool.description.grep": "Search file contents with a pattern.",
        "tool.description.write_file": "Write content to a local file.",
        "tool.description.edit_file": "Edit a local file by replacing text.",
        "tool.description.create_email_draft": "Create a draft in Mail without sending it.",
        "tool.description.create_note_draft": "Create a draft in Notes.",
        "tool.description.get_finder_context": "Read the current Finder folder and selection.",
        "tool.description.get_xcode_context": "Read the active Xcode document path.",
        "tool.description.get_active_browser_url": "Read the active browser tab URL and title.",
        "tool.description.read_image_text": "Extract text from an image using OCR.",
        "tool.description.toggle_system_dark_mode": "Toggle the macOS color scheme.",
        "tool.description.set_system_volume": "Set the macOS system volume.",
        "tool.description.sqlite__sqlite_query": "Query a configured SQLite database.",
        "tool.description.sqlite__sqlite_list_tables": "List SQLite tables.",
        "tool.description.sqlite__sqlite_get_schema": "Read a SQLite table schema.",
        "tool.description.sqlite__sqlite_sample_table": "Sample rows from a SQLite table.",
        "tool.description.filesystem__filesystem_read_file": "Read a file through the Filesystem MCP server.",
        "tool.description.filesystem__filesystem_write_file": "Write a file through the Filesystem MCP server.",
        "tool.description.filesystem__filesystem_list_directory": "List a directory through the Filesystem MCP server.",
        "tool.description.filesystem__filesystem_create_directory": "Create a directory through the Filesystem MCP server.",
        "tool.description.filesystem__filesystem_delete_file": "Delete a file through the Filesystem MCP server.",
        "tool.description.filesystem__filesystem_delete_directory": "Delete a directory through the Filesystem MCP server.",
        "tool.description.filesystem__filesystem_move": "Move a file through the Filesystem MCP server.",
        "tool.description.filesystem__filesystem_get_file_info": "Read file metadata through the Filesystem MCP server.",
        "tool.description.local_kb__search_local_wiki": "Search a local knowledge base.",
        "tool.description.local_kb__list_wiki_pages": "List local knowledge pages.",
        "tool.description.local_kb__read_wiki_page": "Read a local knowledge page.",
        "tool.description.external_rag__search_external_knowledge_base": "Search an external RAG endpoint.",
        "tool.description.across_context__remember_context": "Store durable shared memory in Across Context.",
        "tool.description.across_context__search_context": "Search shared global and project memory.",
        "tool.description.across_context__get_project_context": "Return generated project context from Across Context.",
        "tool.description.across_context__review_pending_memories": "Review automatic memory writes waiting for approval.",
        "tool.description.across_context__approve_memory": "Approve pending memory for future agent use.",
        "tool.description.across_context__get_agent_card": "Inspect Across Context discovery metadata.",
        "tool.description.across_context__export_agent_instructions": "Export project instructions for agent runtimes.",
        "tasks.title": "Task Orchestration",
        "tasks.sidebar": "TASKS",
        "tasks.search": "Search tasks...",
        "tasks.releaseEvaluation": "RELEASE EVALUATION",
        "tasks.releaseEvaluation.refresh": "Refresh release evaluation",
        "tasks.releaseEvaluation.open": "Open Release Evidence Center",
        "tasks.releaseEvaluation.empty": "No quality-gated task evidence yet.",
        "tasks.releaseEvaluation.readiness": "Readiness",
        "tasks.releaseEvaluation.passRate": "Pass",
        "tasks.releaseEvaluation.score": "Score",
        "tasks.releaseEvaluation.trend": "Trend",
        "tasks.releaseEvaluation.delta": "Delta",
        "tasks.releaseEvaluation.agentMix": "Mix",
        "tasks.releaseEvaluation.evaluated": "%d evaluated",
        "tasks.releaseEvaluation.remediations": "%d repaired",
        "tasks.releaseEvaluation.latest": "Latest %s",
        "tasks.releaseEvaluation.probes": "%dP/%dF probes",
        "tasks.releaseEvaluation.readiness.ready": "Ready",
        "tasks.releaseEvaluation.readiness.attention": "Watch",
        "tasks.releaseEvaluation.readiness.blocked": "Blocked",
        "tasks.releaseEvaluation.readiness.no_evidence": "No data",
        "tasks.releaseEvaluation.trend.improving": "Up",
        "tasks.releaseEvaluation.trend.stable": "Flat",
        "tasks.releaseEvaluation.trend.regressing": "Down",
        "tasks.releaseEvaluation.trend.single_point": "New",
        "tasks.releaseEvaluation.trend.no_data": "No data",
        "tasks.releaseE2E.run": "Run Complex E2E",
        "tasks.releaseE2E.starting": "Starting E2E...",
        "tasks.releaseE2E.help": "Start the full release gate scenario",
        "tasks.releaseCenter.title": "Release Evidence Center",
        "tasks.releaseCenter.subtitle": "Audit readiness, probe coverage, agent mix, and task evidence.",
        "tasks.releaseCenter.overview": "Version Readiness",
        "tasks.releaseCenter.repairs": "Repairs",
        "tasks.releaseCenter.risks": "Top Risks",
        "tasks.releaseCenter.checklist": "Readiness Checklist",
        "tasks.releaseCenter.probeCoverage": "Probe Coverage",
        "tasks.releaseCenter.stackCoverage": "Stack Coverage",
        "tasks.releaseCenter.agentCoverage": "Agent Coverage",
        "tasks.releaseCenter.recent": "Recent Evidence",
        "tasks.releaseCenter.openTask": "Open task detail",
        "tasks.evidence.view": "View Evidence Bundle",
        "tasks.evidence.export": "Export Evidence",
        "tasks.evidence.loading": "Loading task evidence...",
        "tasks.evidence.exported": "Evidence exported to %@",
        "tasks.evidence.openExport": "Show File",
        "tasks.evidence.title": "Evidence Bundle",
        "tasks.evidence.audit": "Audit Safety",
        "tasks.evidence.benchmark": "Benchmark",
        "tasks.evidence.expectedFiles": "Expected Files",
        "tasks.evidence.requiredProbes": "Required Probes",
        "tasks.evidence.producedFiles": "Produced Files",
        "tasks.evidence.failures": "Failures",
        "tasks.new": "New Task",
        "tasks.loadMore": "Load More",
        "tasks.loading": "Loading...",
        "tasks.none.title": "No Task Selected",
        "tasks.none.subtitle": "Select a task from the sidebar or create a new one",
        "tasks.backendUnavailable.title": "Backend Unavailable",
        "tasks.backendUnavailable.subtitle": "Task orchestration is temporarily offline. The app will reconnect after the backend restarts.",
        "tasks.backendUnavailable.sidebar": "The backend is offline. Retry after it restarts to reload the task list.",
        "tasks.backendUnavailable.retry": "Retry",
        "tasks.orchestratorPlugin.title": "Across Orchestrator Required",
        "tasks.orchestratorPlugin.subtitle": "Task dispatch is provided by the external Across Orchestrator plugin. Install it to create and run orchestrated tasks.",
        "tasks.orchestratorPlugin.install": "Install Plugin",
        "tasks.orchestratorPlugin.installing": "Installing...",
        "tasks.orchestratorPlugin.retry": "Check Again",
        "tasks.orchestratorPlugin.installDir": "Install location: %@",
        "tasks.decompositionFailed": "Task Decomposition Failed",
        "tasks.unknownError": "Unknown error",
        "tasks.decomposing": "Owner Agent is decomposing the task...",
        "tasks.decomposing.help": "Analyzing requirements with the LLM. This usually takes 10-30 seconds.",
        "tasks.noSubtasks": "No subtasks yet",
        "tasks.restore": "Restore Task",
        "tasks.pause": "Pause",
        "tasks.resume": "Resume",
        "tasks.cancel": "Cancel",
        "tasks.waitingKey": "Waiting for API key sync",
        "tasks.waitingKey.help": "The task will continue after a cloud model API key is saved in Model Settings.",
        "tasks.refreshKeys": "Refresh Keys",
        "tasks.description": "Task Description",
        "tasks.deliveryHealth": "Delivery Health",
        "tasks.delivery": "Delivery",
        "tasks.orchestration": "Orchestration",
        "tasks.required": "Required",
        "tasks.score": "Score",
        "tasks.mode": "Mode",
        "tasks.qualityRemediation": "Quality remediation is running. The task will finalize automatically after repair subtasks finish.",
        "tasks.missingDeliverable": "Missing required deliverable: %@",
        "tasks.failedConstraint": "Failed constraint: %@",
        "tasks.terminalInconsistency": "Terminal inconsistency: %@",
        "tasks.terminalRemediation": "Terminal task still has active quality remediation.",
        "tasks.requiredGateFailures": "Required quality gate failures: %d",
        "tasks.manualGateChecks": "Manual quality checks required: %d",
        "tasks.skippedGateChecks": "Required quality checks skipped: %d",
        "tasks.activeRemediation": "Active remediation: %@",
        "tasks.nextRepair": "Next repair action: %@",
        "tasks.observability": "Execution Evidence",
        "tasks.observability.agents": "Agents",
        "tasks.observability.local": "Local",
        "tasks.observability.cloud": "Cloud",
        "tasks.observability.gates": "Gates",
        "tasks.observability.remediation": "Repairs",
        "tasks.deliveryType": "Delivery Type",
        "tasks.deliveryType.functional": "Functional",
        "tasks.deliveryType.functional.subtitle": "Validate behavior, tests, and runtime evidence",
        "tasks.deliveryType.artifact": "Artifact",
        "tasks.deliveryType.artifact.subtitle": "Validate deliverables, files, and content",
        "tasks.composite": "Composite",
        "tasks.projectDirectory": "Project Directory",
        "tasks.ownerAgent": "Owner Agent",
        "tasks.subtaskAgents": "Subtask Agents",
        "tasks.autoUsesAll": "Auto uses all available",
        "tasks.autoAllSubtask": "Auto: all subtask agents",
        "tasks.strictDependency": "Strict Dependency Mode",
        "tasks.strictDependency.help": "When enabled, failed subtasks block dependent downstream work.",
        "tasks.capabilityPreflight": "Capability Preflight",
        "tasks.capabilityPreflight.empty": "Fill the description and delivery type to preview routing.",
        "tasks.capabilityPreflight.recommended": "Recommended: %@",
        "tasks.capabilityPreflight.matched": "Matched skills: %@",
        "tasks.capabilityPreflight.nativeMatched": "Native skills: %@",
        "tasks.capabilityPreflight.repair": "Repair: %@",
        "tasks.capabilityPreflight.routingEvidence": "Routing evidence: %@",
        "tasks.capabilityPreflight.noMatch": "No strong skill match yet.",
        "tasks.submit.help": "Submit task",
        "tasks.submitting.help": "Submitting task...",
        "tasks.missingFields": "Missing required fields: %@",
        "tasks.field.availableAgent": "Available Agent or Cloud LLM",
        "tasks.field.existingProjectDirectory": "Existing Project Directory",
        "tasks.selectProjectDirectory": "Select Project Directory",
        "tasks.subtasks": "Subtasks (%d)",
        "tasks.progress": "Task Progress",
        "tasks.subtaskDetails": "Subtask Details",
        "tasks.status": "Status",
        "tasks.agent": "Agent",
        "tasks.duration": "Duration",
        "tasks.runningFor": "Running For",
        "tasks.waitingState": "Waiting State",
        "tasks.waitingOn": "Waiting on: %@",
        "tasks.outputFile": "Output File",
        "tasks.errorMessage": "Error Message",
        "tasks.fixPlan": "Fix Plan",
        "tasks.artifacts": "Artifacts",
        "tasks.fixRound": "Fix #%d",
        "tasks.ownerDecision": "Owner Decision",
        "tasks.auto": "Auto",
        "tasks.owner": "Owner Agent",
        "tasks.unknownAgent": "Unknown Agent",
        "status.running": "Running",
        "status.completed": "Completed",
        "status.failed": "Failed",
        "status.completed_with_failures": "Completed with Failures",
        "status.paused": "Paused",
        "status.pending": "Pending",
        "status.suspended": "Suspended",
        "status.decomposing": "Decomposing",
        "status.cancelled": "Cancelled",
        "status.not_started": "Not Started",
        "status.unknown": "Unknown",
        "status.passed": "Passed",
        "status.partial": "Partial",
        "status.recovering": "Recovering",
        "status.healthy": "Healthy",
        "status.inconsistent": "Inconsistent",
        "status.neutral": "Neutral",
        "status.approved": "Approved",
        "status.blocked": "Blocked",
        "status.revalidating": "Revalidating",
        "status.needs_fix": "Needs Fix"
    ],
    "zh-Hans": [
        "settings.title": "设置",
        "settings.subtitle": "管理助手的声音、语言、外观、默认行为和轻量上下文偏好。",
        "settings.diagnostics": "诊断",
        "settings.models": "模型",
        "settings.capabilities": "能力",
        "settings.mcp": "MCP",
        "settings.plugins": "插件中心",
        "settings.tools": "工具",
        "settings.preferences": "设置",
        "settings.savedLocally": "偏好已保存到本机",
        "settings.close": "关闭",
        "settings.refresh": "刷新",
        "diagnostics.title": "启动诊断",
        "diagnostics.subtitle": "检查后端健康、本地路径、Provider 就绪度和打包运行状态。",
        "diagnostics.status": "状态",
        "diagnostics.passed": "通过",
        "diagnostics.warnings": "警告",
        "diagnostics.failed": "失败",
        "diagnostics.checks": "检查项",
        "diagnostics.checks.subtitle": "只读启动检查，并给出明确修复建议。",
        "diagnostics.paths": "本地路径",
        "diagnostics.paths.subtitle": "打包运行时使用的 App 私有数据位置。",
        "diagnostics.runtime": "运行时",
        "diagnostics.runtime.subtitle": "当前后端进程和任务持久化状态。",
        "diagnostics.tasks": "任务",
        "diagnostics.persistence": "持久化",
        "diagnostics.uptime": "运行",
        "diagnostics.headline.passed": "%d 项通过",
        "diagnostics.headline.warnings": "%d 项警告",
        "diagnostics.headline.failed": "%d 项失败",
        "diagnostics.loading": "正在加载启动诊断...",
        "diagnostics.empty": "尚未加载诊断。",
        "diagnostics.openPath": "打开文件夹",
        "diagnostics.status.ready": "就绪",
        "diagnostics.status.attention": "注意",
        "diagnostics.status.blocked": "阻断",
        "diagnostics.status.passed": "通过",
        "diagnostics.status.warning": "警告",
        "diagnostics.status.failed": "失败",
        "diagnostics.status.info": "信息",
        "releaseVerification.title": "RC 验收",
        "releaseVerification.subtitle": "从启动诊断和最新 Release E2E 证据生成发布验收报告。",
        "releaseVerification.run": "运行 RC 验收",
        "releaseVerification.running": "验收中...",
        "releaseVerification.empty": "尚未生成 RC 验收报告。",
        "releaseVerification.latest": "最新 Release E2E",
        "releaseVerification.reportFiles": "报告文件",
        "releaseVerification.remediation": "修复建议",
        "releaseVerification.task": "任务",
        "releaseVerification.benchmark": "基准",
        "releaseVerification.score": "分数",
        "releaseVerification.repairs": "修复",
        "releaseVerification.preReleaseGates": "发版前门禁",
        "releaseVerification.gateSummary": "%d 项通过 · %d 项已配置 · %d 项手动 · %d 项缺失",
        "releaseVerification.missingGatePaths": "缺失的必需门禁路径",
        "releaseVerification.gateParseErrors": "门禁证据解析错误",
        "releaseVerification.morePaths": "另有 %d 个路径",
        "releaseVerification.gateEvidence": "证据",
        "releaseVerification.gateStatus.configured": "已配置",
        "releaseVerification.gateStatus.passed": "已通过",
        "releaseVerification.gateStatus.manual_required": "手动",
        "releaseVerification.gateStatus.missing": "缺失",
        "releaseVerification.gateStatus.failed": "失败",
        "releaseVerification.gateStatus.blocked": "阻塞",
        "releaseVerification.markdown": "Markdown",
        "releaseVerification.json": "JSON",
        "releaseVerification.openReport": "打开报告",
        "section.language": "语言",
        "section.voice": "朗读与声音",
        "section.appearance": "外观",
        "section.window": "窗口与快捷键",
        "section.conversation": "对话默认值",
        "section.privacy": "隐私与上下文",
        "section.advanced": "高级",
        "language.mode": "应用语言",
        "language.mode.help": "默认跟随 macOS；不支持的系统语言会使用英文。",
        "language.followSystem": "跟随系统",
        "language.english": "English",
        "language.simplifiedChinese": "简体中文",
        "voice.summary": "当前声音",
        "voice.source": "声音来源",
        "voice.source.help": "使用 macOS 系统声音、最佳已安装声音，或手动选择已安装声音。",
        "voice.source.system": "系统",
        "voice.source.best": "最佳",
        "voice.source.choose": "选择",
        "voice.autoRead": "自动朗读助手回复",
        "voice.autoRead.help": "除非当前聊天静音，否则自动朗读新的助手消息。",
        "voice.rate": "朗读速度",
        "voice.volume": "音量",
        "voice.test": "测试声音",
        "voice.openSettings": "打开语音设置",
        "voice.refresh": "刷新声音",
        "voice.available": "可用",
        "voice.noVoices": "未找到声音",
        "voice.systemDefault": "系统默认",
        "voice.bestInstalled": "最佳已安装",
        "appearance.scheme": "配色",
        "appearance.scheme.help": "跟随 macOS，或固定使用浅色/深色外观。",
        "appearance.followSystem": "跟随系统",
        "appearance.light": "浅色",
        "appearance.dark": "深色",
        "appearance.reduceMotion": "减少动态效果",
        "appearance.reduceMotion.help": "减少悬停、面板和状态提示等非必要动画。",
        "conversation.rememberAgent": "记住上次选择的 Agent",
        "conversation.rememberAgent.help": "如果上次的 Agent 仍可用，就优先使用它。",
        "conversation.defaultProject": "默认项目",
        "conversation.defaultProject.help": "选择新对话默认进入的位置。",
        "conversation.lastActiveProject": "上次活跃项目",
        "conversation.defaultWorkspace": "默认工作区",
        "privacy.activeApp": "附带当前 App 上下文",
        "privacy.activeApp.help": "可用时附带前台 App 和窗口标题。",
        "privacy.browser": "附带浏览器上下文",
        "privacy.browser.help": "为浏览器标题和 URL 上下文预留。",
        "privacy.openData": "打开数据目录",
        "advanced.socket": "后端 Socket",
        "advanced.logs": "日志目录",
        "advanced.openLogs": "打开日志",
        "screenshot.ocr": "截图识别文字",
        "screenshot.attach": "附加截图",
        "screenshot.copy": "复制截图",
        "screenshot.copied": "截图已复制到剪贴板。",
        "screenshot.cancelled": "截图已取消。",
        "screenshot.copyFailed": "无法将截图复制到剪贴板。",
        "screenshot.permission.ocr": "[提示：首次截图需要“屏幕录制”权限。请在系统弹窗中允许，或前往“系统设置 -> 隐私与安全性 -> 屏幕录制”开启权限。授权后请重启 App。]",
        "screenshot.permission.attach": "[提示：附加截图需要“屏幕录制”权限。请前往“系统设置 -> 隐私与安全性 -> 屏幕录制”开启权限，然后再试一次。]",
        "screenshot.permission.copy": "[提示：复制截图需要“屏幕录制”权限。请前往“系统设置 -> 隐私与安全性 -> 屏幕录制”开启权限，然后再试一次。]",
        "toolbar.voiceInput": "语音输入",
        "toolbar.continuous.enable": "开启连续语音模式",
        "toolbar.continuous.disable": "关闭连续语音模式",
        "toolbar.mute": "静音朗读",
        "toolbar.unmute": "取消静音",
        "toolbar.copyConversation": "复制完整对话",
        "toolbar.tasks": "任务",
        "toolbar.tasks.disabled": "请先配置可用的 Agent 或 LLM",
        "toolbar.models": "模型",
        "toolbar.capabilities": "能力",
        "toolbar.mcp": "MCP 插件",
        "toolbar.plugins": "插件中心",
        "toolbar.tools": "工具权限",
        "toolbar.settings": "设置",
        "attachment.addFiles": "附加文件或文件夹",
        "project.title": "项目",
        "project.new": "新增项目",
        "project.newBlank": "新建空白项目",
        "project.useExisting": "使用已有文件夹",
        "project.loading": "正在加载项目...",
        "project.back": "返回项目",
        "project.collapseAll": "全部折叠",
        "project.refresh": "刷新",
        "project.hideHidden": "隐藏隐藏文件",
        "project.showHidden": "显示隐藏文件",
        "project.newChat": "新建对话",
        "project.newChatInProject": "在此项目中新建对话",
        "project.openTree": "打开目录树",
        "project.noChats": "暂无对话",
        "project.pin": "置顶项目",
        "project.unpin": "取消置顶项目",
        "conversation.pin": "置顶对话",
        "conversation.unpin": "取消置顶对话",
        "conversation.rename": "重命名",
        "conversation.sessionName": "对话名称",
        "conversation.newConversation": "新对话",
        "conversation.deleteSession": "删除对话",
        "conversation.deleteSessions": "删除 %d 个对话",
        "conversation.yesterday": "昨天",
        "chat.loadEarlier": "加载更早的消息...",
        "chat.thinking": "正在思考...",
        "chat.stop": "停止生成",
        "chat.checkingAgents": "正在检查 Agent...",
        "chat.configureModel": "配置模型",
        "chat.assistant": "助手",
        "chat.placeholder.checking": "正在检查可用 Agent...",
        "chat.placeholder.noAgent": "没有可用 Agent。请打开模型设置继续。",
        "chat.placeholder.project": "询问 %@...",
        "chat.placeholder.selectProject": "选择一个项目开始对话...",
        "onboarding.noAgent": "没有可用的 Agent 或 LLM",
        "onboarding.noAgent.help": "请打开模型设置，至少配置一个云端 LLM 或本地 Agent 后再开始对话或创建任务。",
        "onboarding.openModels": "打开模型设置",
        "onboarding.checking": "正在检查可用 Agent 和 LLM...",
        "accessibility.title": "需要辅助功能权限",
        "accessibility.message": "Across Agents Assistant 需要辅助功能权限来读取上下文屏幕信息，例如当前浏览器 URL 或 Finder 选中的文件。\n\n请在系统设置中启用此 App，然后再试一次。",
        "system.cancel": "取消",
        "system.save": "保存",
        "system.delete": "删除",
        "system.retry": "重试",
        "system.browse": "浏览",
        "system.yes": "是",
        "system.no": "否",
        "system.submit": "提交",
        "system.submitting": "提交中...",
        "system.ready": "就绪",
        "system.openSystemSettings": "打开系统设置",
        "menubar.tooltip": "Across Agents Assistant",
        "menubar.showWindow": "显示主窗口",
        "menubar.togglePanel": "切换面板（Option+Tab）",
        "menubar.quit": "退出",
        "models.title": "模型设置",
        "models.localAgent": "本地 Agent",
        "models.cloudLLM": "云端 LLM",
        "models.refreshAll": "全部刷新",
        "models.configured": "已配置",
        "models.notConfigured": "未配置",
        "models.executablePath": "可执行文件路径",
        "models.chooseExecutable": "选择可执行文件",
        "models.autoDetect": "自动检测",
        "models.detecting": "检测中",
        "models.detectingExecutable": "正在检测可执行文件...",
        "models.detectAgent.help": "从配置路径、PATH 和安全系统位置中检测该 Agent",
        "models.apiKey": "API Key",
        "models.baseURL": "Base URL",
        "models.model": "模型",
        "models.autoModel": "自动",
        "models.refreshModels": "刷新模型列表",
        "models.advancedParameters": "高级参数",
        "models.temperature": "Temperature",
        "models.hideApiKey": "隐藏 API Key",
        "models.showApiKey": "显示 API Key",
        "models.deleteConfiguration": "删除配置",
        "models.deleteConfiguration.message": "确定要删除 %@ 的配置吗？这会从本地凭据存储中移除 API Key。",
        "models.status.notFound": "未找到",
        "models.status.notAuthenticated": "未认证",
        "models.status.unavailable": "不可用",
        "models.status.invalidPath": "路径无效",
        "models.warning.invalidPath": "配置的可执行文件路径无效。请选择有效的可执行文件，或留空使用自动检测。",
        "models.warning.unavailable": "已安装，但健康检查失败。请确认该 Agent 已登录，并可完成非交互式任务。",
        "models.warning.claudeAuth": "请在终端运行 claude auth。",
        "models.detected": "已检测到%@。",
        "models.detected.at": "，位置：%@",
        "models.notFoundManual": "未找到可执行文件。如果已安装在其他位置，请手动选择路径。",
        "models.detectedVia": "通过 %@ 检测到：%@",
        "models.detectedPath": "检测到的路径：%@",
        "models.configuredPath": "配置路径：%@",
        "models.noExecutable": "未找到可执行文件。留空会从 PATH 自动检测，或手动选择可执行文件。",
        "models.autoDetectPath": "从 PATH 自动检测",
        "models.chooseExecutableTitle": "选择 %@ 可执行文件",
        "models.choose": "选择",
        "mcp.title": "MCP 插件",
        "mcp.connected": "已连接",
        "mcp.connecting": "连接中",
        "mcp.failed": "失败",
        "mcp.disabled": "已禁用",
        "mcp.disconnected": "未连接",
        "mcp.needsConfiguration": "待配置",
        "mcp.endpointPlaceholder": "输入 API Endpoint URL",
        "mcp.noPath": "未配置路径",
        "mcp.noConfigurationRequired": "无需配置",
        "mcp.customConfiguration": "自定义配置...",
        "mcp.implementation.external": "外部 Across Context 插件",
        "mcp.implementation.standard": "标准 MCP 服务",
        "mcp.plugin.local_kb.name": "本地知识库",
        "mcp.plugin.local_kb.description": "通过 MCP 搜索本地笔记和知识文件。",
        "mcp.plugin.external_rag.name": "外部 RAG",
        "mcp.plugin.external_rag.description": "连接外部检索端点，为对话提供更丰富的上下文。",
        "mcp.plugin.sqlite.name": "SQLite",
        "mcp.plugin.sqlite.description": "让 Agent 检查并查询本地 SQLite 数据库。",
        "mcp.plugin.filesystem.name": "文件系统",
        "mcp.plugin.filesystem.description": "给 Agent 提供受控的文件和文件夹访问能力。",
        "mcp.plugin.across_context.name": "Across Context",
        "mcp.plugin.across_context.description": "让已配置的 Agent 共享持久的本地记忆。",
        "plugins.title": "插件中心",
        "plugins.subtitle": "管理外部 Across 插件、生命周期动作和共享记忆治理。",
        "plugins.versionUnknown": "版本未知",
        "plugins.commandReady": "命令可用",
        "plugins.commandMissing": "命令缺失",
        "plugins.manifestReady": "清单可用",
        "plugins.manifestMissing": "清单缺失",
        "plugins.path.runtime": "运行目录",
        "plugins.path.data": "数据目录",
        "plugins.compatibility": "要求基座",
        "plugins.status.ready": "就绪",
        "plugins.status.installed": "已安装",
        "plugins.status.missing": "未安装",
        "plugins.action.probe": "探测",
        "plugins.action.install": "安装",
        "plugins.action.repair": "修复",
        "plugins.action.uninstall": "卸载",
        "plugins.loop.runtime": "Agent Loop",
        "plugins.loop.v2": "Loop v2",
        "plugins.loop.checkpoints": "检查点",
        "plugins.loop.memoryHooks": "记忆钩子",
        "plugins.loop.probe": "运行 Agent Loop 探测",
        "plugins.loop.status": "Loop %@",
        "plugins.loop.steps": "%d 步",
        "plugins.loop.checkpointCount": "%d 个检查点",
        "plugins.loop.currentAction": "动作 %@",
        "plugins.loop.pendingApproval": "等待批准",
        "plugins.loop.leaseRemaining": "租约 %d 秒",
        "plugins.loop.leaseIdle": "租约空闲",
        "plugins.loop.leaseStale": "租约过期",
        "plugins.loop.cancelRequested": "已请求取消",
        "plugins.loop.cancelAckPending": "等待取消确认",
        "plugins.loop.failureCount": "%d 个失败",
        "plugins.loop.healthDetails": "Loop 健康详情",
        "plugins.loop.detailStatus": "状态",
        "plugins.loop.detailAction": "动作",
        "plugins.loop.detailLease": "租约",
        "plugins.loop.detailHeartbeat": "心跳",
        "plugins.loop.detailCancellation": "取消",
        "plugins.loop.detailFailures": "失败",
        "plugins.loop.detailExecutableActions": "操作",
        "plugins.loop.detailReleaseEvidence": "发版",
        "plugins.loop.detailReleaseCheck": "检查",
        "plugins.loop.detailReleaseRisk": "风险",
        "plugins.loop.detailReleaseNext": "下一步",
        "plugins.loop.detailAudit": "审计",
        "plugins.loop.detailRouting": "路由",
        "plugins.loop.detailRecovery": "恢复",
        "plugins.loop.detailRecoveryPolicy": "策略",
        "plugins.loop.detailRecoveredStep": "已恢复",
        "plugins.loop.detailMemory": "记忆",
        "plugins.loop.detailMemoryCandidate": "候选",
        "plugins.loop.evidenceDetails": "证据详情",
        "plugins.loop.auditComplete": "%d 个事件完整",
        "plugins.loop.auditPartial": "%d 个事件不完整",
        "plugins.loop.routingSummary": "%d 次路由，%d 个提示",
        "plugins.loop.recoverySummary": "%d 个决策，%d 个已应用，%d 个受阻",
        "plugins.loop.recoveryApplied": "已应用",
        "plugins.loop.recoveryBlocked": "受阻",
        "plugins.loop.recoveryAttempt": "第 %d/%d 次",
        "plugins.loop.recoveryAttemptSingle": "第 %d 次",
        "plugins.loop.recoveryMore": "另 %d 个",
        "plugins.loop.recoveredAfter": "%@ 在 %@ 后",
        "plugins.loop.recoveryTurn": "第 %d 轮",
        "plugins.loop.memoryCandidateSummary": "%d 个候选",
        "plugins.loop.memoryCandidateTurn": "第 %d 轮",
        "plugins.loop.releaseEvidenceWithRisks": "%@，%d 个风险",
        "plugins.loop.evidenceMore": "另 %d 个",
        "plugins.loop.renewalCount": "%d 次续租",
        "plugins.loop.none": "无",
        "plugins.loop.events": "事件",
        "plugins.loop.eventsLive": "实时",
        "plugins.loop.eventsSnapshot": "快照",
        "plugins.loop.eventsFallback": "回退",
        "plugins.loop.eventsUnavailable": "不可用",
        "plugins.loop.timelineMode": "时间线模式",
        "plugins.loop.eventSequence": "顺序",
        "plugins.loop.eventId": "事件 ID",
        "plugins.loop.correlationId": "关联",
        "plugins.loop.stepId": "步骤 ID",
        "plugins.loop.actionId": "动作 ID",
        "plugins.loop.taskId": "任务 ID",
        "plugins.loop.subtaskId": "子任务 ID",
        "plugins.memory.title": "共享记忆审核",
        "plugins.memory.subtitle": "审核、归档或遗忘 Across Context 写入的记忆。",
        "plugins.memory.pending": "待审核",
        "plugins.memory.active": "已启用",
        "plugins.memory.archived": "已归档",
        "plugins.memory.all": "全部",
        "plugins.memory.placeholder": "新增一条待审核记忆...",
        "plugins.memory.add": "新增记忆",
        "plugins.memory.empty": "当前筛选条件下没有记忆。",
        "plugins.memory.loopCandidates": "Loop 记忆候选",
        "plugins.memory.loopCandidateCount": "%d 个候选",
        "plugins.memory.focusCandidate": "定位记忆审核",
        "plugins.memory.approve": "启用",
        "plugins.memory.archive": "归档",
        "plugins.memory.forget": "遗忘",
        "capabilities.title": "Agent 能力",
        "capabilities.subtitle": "为每个 Agent 调整技能、插件和工具范围。",
        "capabilities.agents": "AGENT",
        "capabilities.agent.local.available": "本地 Agent 可用",
        "capabilities.agent.local.configurable": "本地 Agent 可配置",
        "capabilities.agent.cloud.available": "云端 LLM 已配置",
        "capabilities.agent.cloud.configurable": "云端 LLM 可配置",
        "capabilities.configuredCount": "已配置 %d 项能力",
        "capabilities.registry": "Orchestrator 注册表",
        "capabilities.registryAgents": "%d 个 Agent",
        "capabilities.registryCapabilities": "%d 项导出能力",
        "capabilities.registryRedacted": "已脱敏",
        "capabilities.registryDescriptor": "信号",
        "capabilities.registryAliases": "别名",
        "capabilities.registryPlugins": "插件",
        "capabilities.registryTools": "工具",
        "capabilities.registryWarnings": "警告",
        "capabilities.registryEmpty": "此 Agent 暂无导出描述。",
        "capabilities.registryRefresh": "刷新注册表",
        "capabilities.registrySynced": "注册表已同步",
        "capabilities.registryDrift": "检测到注册表漂移",
        "capabilities.registryMissing": "缺少注册表描述",
        "capabilities.registryIssueCount": "%d 项检查",
        "capabilities.registryExpected": "预期",
        "capabilities.registryExported": "已导出",
        "capabilities.registryNone": "无",
        "capabilities.registryCheck.descriptor": "描述",
        "capabilities.registryCheck.skills": "技能",
        "capabilities.registryCheck.plugins": "插件",
        "capabilities.registryCheck.tools": "工具",
        "capabilities.registryCheck.nativeSkills": "原生技能",
        "capabilities.registryCheck.strictScope": "严格范围",
        "capabilities.reset": "重置配置",
        "capabilities.skills": "技能",
        "capabilities.plugins": "MCP 插件",
        "capabilities.tools": "工具",
        "capabilities.searchTools": "搜索工具",
        "capabilities.instructions": "自定义指令",
        "capabilities.strictScope": "严格插件/工具范围",
        "capabilities.strictScope.help": "优先只让该 Agent 使用已选择的插件和工具。",
        "capabilities.empty": "选择一个 Agent 来配置能力。",
        "capabilities.customSkillCount": "%d 个自定义技能",
        "capabilities.addSkill": "新增技能",
        "capabilities.customSkill": "自定义",
        "capabilities.deleteSkill": "删除技能",
        "capabilities.newSkill": "新建自定义技能",
        "capabilities.skillName": "名称",
        "capabilities.skillDescription": "描述",
        "capabilities.skillPromptHint": "提示词指导",
        "capabilities.skillTags": "标签",
        "capabilities.skillTags.placeholder": "frontend, quality",
        "capabilities.createSkill": "创建",
        "capabilities.nativeSkills": "原生技能",
        "capabilities.nativeSkillCount": "已安装 %d 个",
        "capabilities.nativeSkills.empty": "暂无已安装原生技能。",
        "capabilities.nativeSkills.create": "创建 Claude 技能",
        "capabilities.nativeSkills.install": "安装原生技能",
        "capabilities.nativeSkills.identifier": "技能标识",
        "capabilities.nativeSkills.force": "强制",
        "capabilities.nativeSkills.apply": "应用",
        "capabilities.nativeSkills.update": "更新技能",
        "capabilities.nativeSkills.uninstall": "卸载技能",
        "capabilities.nativeSkills.health": "可用原生技能 / 原生技能总数",
        "capabilities.nativeSkills.mode.directory": "目录",
        "capabilities.nativeSkills.mode.cli": "CLI",
        "capabilities.nativeSkills.source.native": "原生",
        "capabilities.nativeSkills.unavailable": "不可用",
        "capabilities.skill.general_execution.name": "通用执行",
        "capabilities.skill.general_execution.description": "处理实现、文件修改和命令行操作。",
        "capabilities.skill.macos_automation.name": "macOS 自动化",
        "capabilities.skill.macos_automation.description": "操作 Finder、Xcode、浏览器、笔记和截图上下文。",
        "capabilities.skill.frontend_design.name": "前端产品设计",
        "capabilities.skill.frontend_design.description": "设计并实现贴合产品风格的精致界面。",
        "capabilities.skill.interaction_design.name": "交互设计",
        "capabilities.skill.interaction_design.description": "优化工作流、键盘路径、空状态和反馈。",
        "capabilities.skill.backend_api.name": "后端 API 实现",
        "capabilities.skill.backend_api.description": "构建 API、校验、持久化和集成逻辑。",
        "capabilities.skill.data_modeling.name": "数据建模",
        "capabilities.skill.data_modeling.description": "设计数据结构、迁移、索引和一致性约束。",
        "capabilities.skill.architecture_review.name": "架构评审",
        "capabilities.skill.architecture_review.description": "规划模块边界、契约和技术取舍。",
        "capabilities.skill.code_review.name": "代码评审",
        "capabilities.skill.code_review.description": "检查正确性、回归风险、边界条件和可维护性。",
        "capabilities.skill.test_strategy.name": "测试策略",
        "capabilities.skill.test_strategy.description": "设计面向行为和跨模块契约的验证方案。",
        "capabilities.skill.test_authoring.name": "测试编写",
        "capabilities.skill.test_authoring.description": "编写自动化测试、夹具和确定性检查。",
        "capabilities.skill.devops_release.name": "DevOps 与发布",
        "capabilities.skill.devops_release.description": "处理打包、CI、部署、签名和发布准备。",
        "capabilities.skill.integration_smoke.name": "集成冒烟",
        "capabilities.skill.integration_smoke.description": "验证多个交付部分是否能真实协作。",
        "tools.title": "工具权限",
        "tools.empty.title": "暂无已授权工具",
        "tools.empty.description": "当你勾选“不再询问”并批准工具后，它们会出现在这里。",
        "tools.noData": "没有数据",
        "tools.parseFailed": "解析失败：%@",
        "tools.today": "今天 %@",
        "tools.yesterday": "昨天 %@",
        "tools.filter.all": "全部",
        "tools.filter.local": "本机工具",
        "tools.filter.mcp": "MCP 工具",
        "tools.local.section": "本机工具",
        "tools.mcp.section": "MCP 工具",
        "tools.local.meta": "直接操作当前 Mac · %d 个工具",
        "tools.mcp.meta": "来自已配置服务器 · %d 个工具",
        "tools.mcp.noRuntimeTools": "暂无可用 MCP 工具。请先在上方配置并连接服务器。",
        "tools.permission.alwaysAllow": "永久授权",
        "tools.permission.askEveryTime": "每次询问",
        "tools.permission.unavailable": "不可用",
        "tools.risk.low": "低风险",
        "tools.risk.medium": "中风险",
        "tools.risk.high": "高风险",
        "tools.risk.unknown": "未知风险",
        "tools.updateFailed": "无法更新权限：%@",
        "approval.title": "允许助手调用工具？",
        "approval.tool": "工具",
        "approval.risk": "风险",
        "approval.macos": "macOS",
        "approval.macos.system": "系统权限由 macOS 控制。",
        "approval.macos.screenRecording": "屏幕录制权限由 macOS 控制。",
        "approval.macos.accessibility": "辅助功能权限由 macOS 控制。",
        "approval.macos.automation": "自动化权限由 macOS 控制。",
        "approval.deny": "拒绝",
        "approval.allowOnce": "本次授权",
        "approval.alwaysAllow": "永久授权",
        "tool.name.create_email_draft": "创建邮件草稿",
        "tool.name.get_finder_context": "获取 Finder 上下文",
        "tool.name.take_screenshot_and_ocr": "截图识别文字",
        "tool.name.read_image_text": "图片识别文字",
        "tool.name.verify_tool": "验证工具",
        "tool.name.open_url": "打开 URL",
        "tool.name.get_current_browser_url": "获取浏览器 URL",
        "tool.name.get_active_browser_url": "获取浏览器 URL",
        "tool.name.send_claude_code_prompt": "发送 Claude Code 提示",
        "tool.name.list_directory": "列出目录",
        "tool.name.create_note_draft": "创建笔记草稿",
        "tool.name.get_xcode_context": "获取 Xcode 上下文",
        "tool.name.toggle_system_dark_mode": "切换深色模式",
        "tool.name.set_system_volume": "设置系统音量",
        "tool.name.read_file": "读取文件",
        "tool.name.write_file": "写入文件",
        "tool.name.edit_file": "编辑文件",
        "tool.name.grep": "搜索文件内容",
        "tool.name.search_files": "搜索文件",
        "tool.name.sqlite__read_query": "执行 SQL 查询",
        "tool.name.sqlite__sqlite_query": "执行 SQL 查询",
        "tool.name.sqlite__create_table": "创建数据库表",
        "tool.name.sqlite__list_tables": "列出数据库表",
        "tool.name.sqlite__sqlite_list_tables": "列出数据库表",
        "tool.name.sqlite__describe_table": "查看表结构",
        "tool.name.sqlite__sqlite_get_schema": "查看表结构",
        "tool.name.sqlite__append_insight": "追加洞察",
        "tool.name.sqlite__sqlite_sample_table": "抽样数据表",
        "tool.name.filesystem__filesystem_read_file": "读取文件",
        "tool.name.filesystem__filesystem_write_file": "写入文件",
        "tool.name.filesystem__filesystem_list_directory": "列出目录",
        "tool.name.filesystem__filesystem_create_directory": "创建目录",
        "tool.name.filesystem__filesystem_delete_file": "删除文件",
        "tool.name.filesystem__filesystem_delete_directory": "删除目录",
        "tool.name.filesystem__filesystem_move": "移动文件",
        "tool.name.filesystem__filesystem_get_file_info": "获取文件信息",
        "tool.name.filesystem__get_file_info": "获取文件信息",
        "tool.name.filesystem__create_directory": "创建目录",
        "tool.name.filesystem__move_file": "移动文件",
        "tool.name.filesystem__copy_file": "复制文件",
        "tool.name.filesystem__delete_file": "删除文件",
        "tool.name.filesystem__file_tree": "浏览文件树",
        "tool.name.local_kb__search_local_wiki": "搜索本地知识库",
        "tool.name.local_kb__list_wiki_pages": "列出知识页面",
        "tool.name.local_kb__get_wiki_page": "打开知识页面",
        "tool.name.local_kb__read_wiki_page": "打开知识页面",
        "tool.name.external_rag__search_external_knowledge_base": "搜索外部知识库",
        "tool.name.across_context__remember_context": "写入共享记忆",
        "tool.name.across_context__search_context": "搜索共享记忆",
        "tool.name.across_context__get_project_context": "获取项目上下文",
        "tool.name.across_context__review_pending_memories": "查看待确认记忆",
        "tool.name.across_context__approve_memory": "批准记忆",
        "tool.name.across_context__get_agent_card": "获取 Agent Card",
        "tool.name.across_context__export_agent_instructions": "导出 Agent 指令",
        "tool.category.sqlite": "SQLite 操作",
        "tool.category.filesystem": "文件系统操作",
        "tool.category.local_kb": "知识库操作",
        "tool.category.across_context": "共享记忆操作",
        "tool.category.email": "邮件操作",
        "tool.category.browser": "浏览器操作",
        "tool.category.finder": "Finder 操作",
        "tool.category.xcode": "Xcode 操作",
        "tool.category.appearance": "外观设置",
        "tool.category.audio": "音频控制",
        "tool.category.note": "笔记操作",
        "tool.description.list_directory": "列出本机目录内容，用于理解项目结构或当前工作区。",
        "tool.description.search_files": "按文件名规则搜索本机文件。",
        "tool.description.read_file": "读取本机文本文件内容。",
        "tool.description.grep": "按模式搜索文件内容并返回上下文。",
        "tool.description.write_file": "向本机文件写入内容。",
        "tool.description.edit_file": "通过替换文本编辑本机文件。",
        "tool.description.create_email_draft": "在邮件中创建草稿，不会自动发送，需要用户最终确认。",
        "tool.description.create_note_draft": "在备忘录中创建草稿。",
        "tool.description.get_finder_context": "读取当前 Finder 目录和已选文件。",
        "tool.description.get_xcode_context": "读取 Xcode 当前活动文档路径。",
        "tool.description.get_active_browser_url": "读取当前浏览器标签页的标题和 URL。",
        "tool.description.read_image_text": "使用 OCR 识别图片中的文字。",
        "tool.description.toggle_system_dark_mode": "切换 macOS 系统外观。",
        "tool.description.set_system_volume": "设置 macOS 系统音量。",
        "tool.description.sqlite__sqlite_query": "查询已配置的 SQLite 数据库。",
        "tool.description.sqlite__sqlite_list_tables": "列出 SQLite 数据库表。",
        "tool.description.sqlite__sqlite_get_schema": "读取 SQLite 表结构。",
        "tool.description.sqlite__sqlite_sample_table": "抽样读取 SQLite 表数据。",
        "tool.description.filesystem__filesystem_read_file": "通过文件系统 MCP 服务器读取文件。",
        "tool.description.filesystem__filesystem_write_file": "通过文件系统 MCP 服务器写入文件。",
        "tool.description.filesystem__filesystem_list_directory": "通过文件系统 MCP 服务器列出目录。",
        "tool.description.filesystem__filesystem_create_directory": "通过文件系统 MCP 服务器创建目录。",
        "tool.description.filesystem__filesystem_delete_file": "通过文件系统 MCP 服务器删除文件。",
        "tool.description.filesystem__filesystem_delete_directory": "通过文件系统 MCP 服务器删除目录。",
        "tool.description.filesystem__filesystem_move": "通过文件系统 MCP 服务器移动文件。",
        "tool.description.filesystem__filesystem_get_file_info": "通过文件系统 MCP 服务器读取文件元信息。",
        "tool.description.local_kb__search_local_wiki": "搜索本地知识库内容。",
        "tool.description.local_kb__list_wiki_pages": "列出本地知识库页面。",
        "tool.description.local_kb__read_wiki_page": "读取本地知识库页面。",
        "tool.description.external_rag__search_external_knowledge_base": "搜索外部 RAG 知识库端点。",
        "tool.description.across_context__remember_context": "向 Across Context 写入持久共享记忆。",
        "tool.description.across_context__search_context": "搜索全局和项目级共享记忆。",
        "tool.description.across_context__get_project_context": "从 Across Context 获取生成的项目上下文。",
        "tool.description.across_context__review_pending_memories": "查看等待确认的自动记忆写入。",
        "tool.description.across_context__approve_memory": "批准待确认记忆，供后续 Agent 使用。",
        "tool.description.across_context__get_agent_card": "查看 Across Context 的发现元数据。",
        "tool.description.across_context__export_agent_instructions": "为 Agent 运行时导出项目指令。",
        "tasks.title": "任务编排",
        "tasks.sidebar": "任务",
        "tasks.search": "搜索任务...",
        "tasks.releaseEvaluation": "发布评估",
        "tasks.releaseEvaluation.refresh": "刷新发布评估",
        "tasks.releaseEvaluation.open": "打开发布证据中心",
        "tasks.releaseEvaluation.empty": "暂无质量门任务证据。",
        "tasks.releaseEvaluation.readiness": "状态",
        "tasks.releaseEvaluation.passRate": "通过",
        "tasks.releaseEvaluation.score": "评分",
        "tasks.releaseEvaluation.trend": "趋势",
        "tasks.releaseEvaluation.delta": "变化",
        "tasks.releaseEvaluation.agentMix": "协作",
        "tasks.releaseEvaluation.evaluated": "已评估 %d",
        "tasks.releaseEvaluation.remediations": "已修复 %d",
        "tasks.releaseEvaluation.latest": "最近 %s",
        "tasks.releaseEvaluation.probes": "探针 %d过/%d失",
        "tasks.releaseEvaluation.readiness.ready": "就绪",
        "tasks.releaseEvaluation.readiness.attention": "关注",
        "tasks.releaseEvaluation.readiness.blocked": "阻断",
        "tasks.releaseEvaluation.readiness.no_evidence": "无数据",
        "tasks.releaseEvaluation.trend.improving": "上升",
        "tasks.releaseEvaluation.trend.stable": "平稳",
        "tasks.releaseEvaluation.trend.regressing": "下降",
        "tasks.releaseEvaluation.trend.single_point": "新增",
        "tasks.releaseEvaluation.trend.no_data": "无数据",
        "tasks.releaseE2E.run": "运行复杂 E2E",
        "tasks.releaseE2E.starting": "正在启动 E2E...",
        "tasks.releaseE2E.help": "启动完整发布门禁场景",
        "tasks.releaseCenter.title": "发布证据中心",
        "tasks.releaseCenter.subtitle": "审计就绪度、探针覆盖、Agent 协作和任务证据。",
        "tasks.releaseCenter.overview": "版本就绪度",
        "tasks.releaseCenter.repairs": "修复",
        "tasks.releaseCenter.risks": "主要风险",
        "tasks.releaseCenter.checklist": "就绪清单",
        "tasks.releaseCenter.probeCoverage": "探针覆盖",
        "tasks.releaseCenter.stackCoverage": "技术栈覆盖",
        "tasks.releaseCenter.agentCoverage": "Agent 覆盖",
        "tasks.releaseCenter.recent": "最近证据",
        "tasks.releaseCenter.openTask": "打开任务详情",
        "tasks.evidence.view": "查看证据包",
        "tasks.evidence.export": "导出证据",
        "tasks.evidence.loading": "正在加载任务证据...",
        "tasks.evidence.exported": "证据已导出到 %@",
        "tasks.evidence.openExport": "显示文件",
        "tasks.evidence.title": "证据包",
        "tasks.evidence.audit": "审计安全",
        "tasks.evidence.benchmark": "基准评估",
        "tasks.evidence.expectedFiles": "预期文件",
        "tasks.evidence.requiredProbes": "必需探针",
        "tasks.evidence.producedFiles": "已产出文件",
        "tasks.evidence.failures": "失败项",
        "tasks.new": "新建任务",
        "tasks.loadMore": "加载更多",
        "tasks.loading": "加载中...",
        "tasks.none.title": "未选择任务",
        "tasks.none.subtitle": "从左侧选择任务，或创建一个新任务",
        "tasks.backendUnavailable.title": "后端不可用",
        "tasks.backendUnavailable.subtitle": "任务编排服务暂时离线。后端重启后，应用会重新连接。",
        "tasks.backendUnavailable.sidebar": "后端暂时离线。重启完成后可重试加载任务列表。",
        "tasks.backendUnavailable.retry": "重试",
        "tasks.orchestratorPlugin.title": "需要安装 Across Orchestrator",
        "tasks.orchestratorPlugin.subtitle": "任务下发由外部 Across Orchestrator 插件提供。安装后即可创建和运行编排任务。",
        "tasks.orchestratorPlugin.install": "安装插件",
        "tasks.orchestratorPlugin.installing": "正在安装...",
        "tasks.orchestratorPlugin.retry": "重新检查",
        "tasks.orchestratorPlugin.installDir": "安装位置：%@",
        "tasks.decompositionFailed": "任务拆解失败",
        "tasks.unknownError": "未知错误",
        "tasks.decomposing": "Owner Agent 正在拆解任务...",
        "tasks.decomposing.help": "正在使用 LLM 分析需求，通常需要 10-30 秒。",
        "tasks.noSubtasks": "暂无子任务",
        "tasks.restore": "恢复任务",
        "tasks.pause": "暂停",
        "tasks.resume": "继续",
        "tasks.cancel": "取消",
        "tasks.waitingKey": "等待 API Key 同步",
        "tasks.waitingKey.help": "在模型设置中保存云端模型 API Key 后，任务会继续执行。",
        "tasks.refreshKeys": "刷新 Key",
        "tasks.description": "任务描述",
        "tasks.deliveryHealth": "任务交付",
        "tasks.delivery": "交付",
        "tasks.orchestration": "编排",
        "tasks.required": "必需",
        "tasks.score": "评分",
        "tasks.mode": "模式",
        "tasks.qualityRemediation": "质量修复正在运行。修复子任务完成后，任务会自动收尾。",
        "tasks.missingDeliverable": "缺少必需交付物：%@",
        "tasks.failedConstraint": "约束失败：%@",
        "tasks.terminalInconsistency": "终态不一致：%@",
        "tasks.terminalRemediation": "终态任务仍有活跃的质量修复。",
        "tasks.requiredGateFailures": "必需质量门禁失败：%d",
        "tasks.manualGateChecks": "需要人工确认的质量检查：%d",
        "tasks.skippedGateChecks": "已跳过的必需质量检查：%d",
        "tasks.activeRemediation": "活跃修复：%@",
        "tasks.nextRepair": "下一步修复动作：%@",
        "tasks.observability": "执行证据",
        "tasks.observability.agents": "Agent",
        "tasks.observability.local": "本地",
        "tasks.observability.cloud": "云端",
        "tasks.observability.gates": "门禁",
        "tasks.observability.remediation": "修复",
        "tasks.deliveryType": "交付类型",
        "tasks.deliveryType.functional": "功能",
        "tasks.deliveryType.functional.subtitle": "验证行为、测试和运行证据",
        "tasks.deliveryType.artifact": "产物",
        "tasks.deliveryType.artifact.subtitle": "验证交付物、文件和内容",
        "tasks.composite": "组合",
        "tasks.projectDirectory": "项目目录",
        "tasks.ownerAgent": "Owner Agent",
        "tasks.subtaskAgents": "子任务 Agent",
        "tasks.autoUsesAll": "自动使用全部可用 Agent",
        "tasks.autoAllSubtask": "自动：全部子任务 Agent",
        "tasks.strictDependency": "严格依赖模式",
        "tasks.strictDependency.help": "开启后，失败的子任务会阻塞下游依赖任务。",
        "tasks.capabilityPreflight": "能力预检",
        "tasks.capabilityPreflight.empty": "填写任务描述和交付类型后预览路由。",
        "tasks.capabilityPreflight.recommended": "推荐：%@",
        "tasks.capabilityPreflight.matched": "匹配技能：%@",
        "tasks.capabilityPreflight.nativeMatched": "原生技能：%@",
        "tasks.capabilityPreflight.repair": "修复建议：%@",
        "tasks.capabilityPreflight.routingEvidence": "路由证据：%@",
        "tasks.capabilityPreflight.noMatch": "暂未匹配到强技能。",
        "tasks.submit.help": "提交任务",
        "tasks.submitting.help": "正在提交任务...",
        "tasks.missingFields": "缺少必填字段：%@",
        "tasks.field.availableAgent": "可用 Agent 或云端 LLM",
        "tasks.field.existingProjectDirectory": "存在的项目目录",
        "tasks.selectProjectDirectory": "选择项目目录",
        "tasks.subtasks": "子任务（%d）",
        "tasks.progress": "任务进度",
        "tasks.subtaskDetails": "子任务详情",
        "tasks.status": "状态",
        "tasks.agent": "Agent",
        "tasks.duration": "耗时",
        "tasks.runningFor": "已运行",
        "tasks.waitingState": "等待状态",
        "tasks.waitingOn": "等待：%@",
        "tasks.outputFile": "输出文件",
        "tasks.errorMessage": "错误信息",
        "tasks.fixPlan": "修复计划",
        "tasks.artifacts": "任务产物",
        "tasks.fixRound": "修复 #%d",
        "tasks.ownerDecision": "Owner 决策",
        "tasks.auto": "自动",
        "tasks.owner": "Owner Agent",
        "tasks.unknownAgent": "未知 Agent",
        "status.running": "运行中",
        "status.completed": "已完成",
        "status.failed": "失败",
        "status.completed_with_failures": "部分失败",
        "status.paused": "已暂停",
        "status.pending": "等待中",
        "status.suspended": "已挂起",
        "status.decomposing": "拆解中",
        "status.cancelled": "已取消",
        "status.not_started": "未开始",
        "status.unknown": "未知",
        "status.passed": "通过",
        "status.partial": "部分完成",
        "status.recovering": "修复中",
        "status.healthy": "健康",
        "status.inconsistent": "不一致",
        "status.neutral": "中性",
        "status.approved": "已通过",
        "status.blocked": "已阻塞",
        "status.revalidating": "重新验证中",
        "status.needs_fix": "需要修复"
    ]
]
